export const statNames = [
  "MK8_POS",
  "MK8_DAY",
  "RL_SCORE",
  "RL_GOALS",
  "RL_ASSISTS",
  "RL_SAVES",
  "RL_SHOTS",
  "RL_DAY",
  "COD_KILLS",
  "COD_DEATHS",
  "COD_SCORE",
  "COD_POS",
  "COD_MELEES",
  "LC_DEATHS",
  "SR_WINS",
  "SR_SETS",
  "SR_POS",
  "MR_KILLS",
  "MR_DEATHS",
  "MR_ASSISTS",
  "MR_TRIPLE_KILL",
  "MR_QUADRA_KILL",
  "MR_PENTA_KILL",
  "MR_HEXA_KILL",
  "MR_MEDALS",
  "MR_HIGHEST_DMG",
  "MR_HIGHEST_DMG_BLOCKED",
  "MR_MOST_HEALING",
  "MR_MOST_ASSISTS_FIST",
  "MR_FINAL_HITS",
  "MR_DMG",
  "MR_DMG_BLOCKED",
  "MR_HEALING",
  "MR_ACCURACY",
] as const;

export type StatName = (typeof statNames)[number];
