export enum PostHogEvents {
  SIGN_IN = "signin",
  SIGN_OUT = "signout",
  NAN_ERROR = "NaN Error",
  ADMIN_FORM_SUBMISSION_SUCCESS = "ADMIN_FORM_SUBMISSION_SUCCESS",
  FEEDBACK_FORM_SUBMISSION_SUCCESS = "FEEDBACK_FORM_SUBMISSION_SUCCESS",
  MVP_UPDATE_SUCCESS = "MVP_UPDATE_SUCCESS",
  DRIVE_READ_SUCCESS = "drive-read-success",
  GOOGLE_DRIVE_SUMMARY_GENERATION_SUCCESS = "Google Drive Summary Generation Success",
}

